name: Load Nix
description: Load nix and make a call to clear out all the output on first run
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Pre-Load Nix
      shell: bash
      run: |
        nix develop -c sh -c "echo \"load\""
